blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView
app_name = BlogConfig.name

urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('detail/<int:pk>', BlogDetailView.as_view(), name='detail_blog'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='update_blog'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete_blog')
]

catalog/urls.py
from django.urls import path

from catalog.apps import CatalogConfig
from catalog.views import HomeView, contacts, ProductView, CategoryView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', contacts, name='contacts'),
    path('category/', CategoryView.as_view(), name='category'),
    path('<int:pk>/product/', ProductView.as_view(), name='product')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=250, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/', verbose_name='Превью', **NULLABLE)
    create_date = models.DateTimeField(verbose_name='Дата создания', auto_now=True)
    is_published = models.BooleanField(default=False, verbose_name='опубликовано')
    views_count = models.PositiveSmallIntegerField(default=0, verbose_name='Количество просмотров', editable=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ['-create_date']

catalog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    preview = models.ImageField(upload_to='previews/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.PositiveSmallIntegerField(verbose_name='Цена')
    create_date = models.DateField(verbose_name='Дата создания', auto_now_add=True)
    last_modified_date = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование', **NULLABLE)
    description = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

blog/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from pytils.translit import slugify
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.models import Blog


# Create your views here.
class BlogView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'body', 'is_published']
    success_url = reverse_lazy('blog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save()
            new_post.slug = slugify(new_post.title)
            new_post.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'body', 'is_published']

    def get_success_url(self):
        return reverse('blog:detail_blog', args=[self.object.pk])


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')

catalog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from catalog.models import Category, Product


class HomeView(TemplateView):
    template_name = 'catalog/home.html'
    extra_context = {
        'title': "It`s all in the DNA"
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Category.objects.all()[:3]
        return context_data


class CategoryView(ListView):
    model = Category


class ProductView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Новый контакт!\n{name} ({phone}) написал: {message}\n')
    return render(request, 'catalog/contacts.html')

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post">
        <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog"
             id="modalChoice">
            <div class="modal-dialog" role="document">
                <div class="modal-content rounded-3 shadow">
                    <div class="modal-body p-4 text-center">
                        {% csrf_token %}
                        <h5 class="mb-0">Точно удаляем?</h5>
                        <p class="mb-0"></p>
                    </div>
                    <div class="modal-footer flex-nowrap p-0">
                        <button type="submit"
                                class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                            <strong>Да, точно</strong>
                        </button>
                        <button type="button"
                                class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0"
                                data-bs-dismiss="modal">
                            <a href="{% url 'blog:detail_blog' object.pk %}">Я передумал</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}

{% load tags %}

{% block content %}

    <div class="container-fluid px-3 mt-5">
        <div class="row justify-content-center">
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        <div class="d-inline-flex mb-2 text-muted">Просмотров: {{ object.views_count }}</div>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">{{ object.body }}</p>
                        <p class="card-text"><small class="text-body-secondary">{{ object.create_date }}</small></p>
                    </div>
                    <img src="{{ object.preview|mediapath }}" height="250" width="250" class="card-img-bottom" >
                </div>
            </div>
        </div>
    </div>

    <div class="container text-center mt-5">
        <div class="row justify-content-center">
            <div class="col-4">
                <a href="{% url 'blog:update_blog' object.pk %}" class="btn btn-outline-dark">Редактировать запись</a>
                <a href="{% url 'blog:delete_blog' object.pk %}" class="btn btn-outline-danger">Удалить запись</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="container-fluid px-3 mt-5">
            <div class="row justify-content-center">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            {% if object %}
                                Редактирование записи
                            {% else %}
                                Добавление записи
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Добавить
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% load tags %}

{% block content %}
    <div class="col-12 m-md-3">
        <a href="{% url 'blog:create_blog' %}" class="btn btn-primary">Добавить запись</a>
    </div>
    <div class="row mb-2">
        {% for object in object_list %}
            {#            {% if object.is_published %}#}
            <div class="col-md-6 ">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary-emphasis">Просмотров: {{ object.views_count }}</strong>
                        <h3 class="mb-0">{{ object.title }}</h3>
                        <div class="mb-1 text-body-secondary">{{ object.create_date }}</div>
                        <p class="card-text mb-auto">{{ object.body|slice:100 }}</p>
                        <a href="{% url 'blog:detail_blog' object.pk %}"
                           class="icon-link gap-1 icon-link-hover stretched-link">
                            Продолжить чтение
                            <svg class="bi">
                                <use xlink:href="#chevron-right"></use>
                            </svg>
                        </a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="250" height="250">
                            <img src="{{ object.preview|mediapath }}" height="250" width="250"
                                 alt="Все будет, но не сразу">
                        </svg>
                    </div>
                </div>
            </div>
            {#            {% endif %}#}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Пёпс &hearts;</title>


        <link rel="stylesheet" href="{% static 'css/css@3.css' %}">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
</head>
<body>
{#<svg xmlns="http://www.w3.org/2000/svg" class="d-none">#}
{#    <symbol id="check2" viewBox="0 0 16 16">#}
{#        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>#}
{#    </symbol>#}
{#    <symbol id="circle-half" viewBox="0 0 16 16">#}
{#        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>#}
{#    </symbol>#}
{#    <symbol id="moon-stars-fill" viewBox="0 0 16 16">#}
{#        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>#}
{#        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>#}
{#    </symbol>#}
{#    <symbol id="sun-fill" viewBox="0 0 16 16">#}
{#        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>#}
{#    </symbol>#}
{#</svg>#}

<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
            stroke-width="2" viewBox="0 0 24 24">
        <circle cx="12" cy="12" r="10"></circle>
        <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94"></path>
    </symbol>
    <symbol id="cart" viewBox="0 0 16 16">
        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
    </symbol>
    <symbol id="chevron-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"></path>
    </symbol>
</svg>

<nav class="navbar navbar-expand-md bg-dark sticky-top border-bottom" data-bs-theme="dark">
    <div class="container">
        <div class="offcanvas-body">
            <ul class="navbar-nav flex-grow-1 justify-content-between">
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:home' %}">Домашняя страница</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:category' %}">Услуги</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog' %}">Блог</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                <li class="nav-item"><a class="nav-link disabled">В разработке</a></li>
                <svg class="bi" width="24" height="24">
                    <use xlink:href="#cart"/>
                </svg>
            </ul>
        </div>
    </div>
</nav>

<main>

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:category' %}">Для собак</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:blog' %}">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post">
        <div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog"
             id="modalChoice">
            <div class="modal-dialog" role="document">
                <div class="modal-content rounded-3 shadow">
                    <div class="modal-body p-4 text-center">
                        {% csrf_token %}
                        <h5 class="mb-0">Точно удаляем?</h5>
                        <p class="mb-0"></p>
                    </div>
                    <div class="modal-footer flex-nowrap p-0">
                        <button type="submit"
                                class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0 border-end">
                            <strong>Да, точно</strong>
                        </button>
                        <button type="button"
                                class="btn btn-lg btn-link fs-6 text-decoration-none col-6 py-3 m-0 rounded-0"
                                data-bs-dismiss="modal">
                            <a href="{% url 'detail_blog' object.pk %}">Я передумал</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% load tags %}

{% block content %}
    <div class="col-12 m-md-3">
        <a href="{% url 'create_blog' %}" class="btn btn-primary">Добавить запись</a>
    </div>
    <div class="row mb-2">
        {% for object in object_list %}
{#            {% if object.is_published %}#}
            <div class="col-md-6 ">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary-emphasis">Просмотров: {{ object.views_count }}</strong>
                        <h3 class="mb-0">{{ object.title }}</h3>
                        <div class="mb-1 text-body-secondary">{{ object.create_date }}</div>
                        <p class="card-text mb-auto">{{ object.body|slice:100 }}</p>
                        <a href="{% url 'detail_blog' object.pk %}"
                           class="icon-link gap-1 icon-link-hover stretched-link">
                            Продолжить чтение
                            <svg class="bi">
                                <use xlink:href="#chevron-right"></use>
                            </svg>
                        </a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <svg class="bd-placeholder-img" width="250" height="250">
                            <img src="{{ object.preview|mediapath }}" height="250" width="250"
                                 alt="Все будет, но не сразу">
                        </svg>
                    </div>
                </div>
            </div>
{#            {% endif %}#}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container text-center">
        <div class="row gx-5 mt-5">
                {% include 'catalog/includes/inc_category.html' %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container text-center">
        <div class="row gx-5 mt-5">
                {% include 'catalog/includes/inc_category.html' %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <div class="row gx-5 justify-content-center">
            <div class="col-4">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-light">
                            <tr>
                                <td class="w-25">Почта</td>
                                <td>wow@sky.pro</td>
                            </tr>
                            <tr>
                                <td class="w-25">Телефон</td>
                                <td>8-800-555-35-35</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИП</td>
                                <td>Есть</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"/>
                            </div>
                            <div class="mb-3">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone"
                                       placeholder="Контактный телефон"/>
                            </div>
                            <div class="mb-3">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message"
                                          placeholder="Сообщение"></textarea>
                            </div>
                            <input type="submit" value="Отправить" class="btn btn-lg btn-block btn-outline-primary"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h5 class="display-4">{{ title }}</h5>
    </div>
    <div class="container text-center">
        <div class="row gx-5 mt-5">
                {% include 'catalog/includes/inc_category.html' %}
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/includes/inc_category.html
<div class="container text-center">
    <div class="row gx-5 mt-5">
        {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ object.description|slice:100 }}</li>
                        </ul>
                        <button type="button" class="btn btn-lg btn-block btn-outline-primary">
                            <a href="{% url 'catalog:product' object.pk %}">Перейти</a>
                        </button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load tags %}
{% block content %}
    {% for object in object_list %}
        <div class="container text-center">
            <div class="row gx-5 mt-5 justify-content-center">
                <div class="col-9">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                        </div>
                        <div class="card-body">
{#                            <img src="{{ object.preview|mediapath }}" width="220" height="250">#}
                            <img src="{% mediapath object.preview %}" width="220" height="250" alt="Все будет, но не сразу">
                            <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ object.description|slice:200 }}</li>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}